name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Archlinux CMake builder
      uses: codehz/arch-cmake-builder@v0.2
      with:
        args: "CC=musl-gcc"
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        # Directory containing files to upload
        path: dist
